export default {
  APP_ERROR: "APP_ERROR",
  APP_ERROR_CLOSE: "APP_ERROR_CLOSE",
  APP_INFO: "APP_INFO",
  APP_INFO_CLOSE: "APP_INFO_CLOSE",
  APP_SIGN_IN: "APP_SIGN_IN",
  APP_SIGN_OUT: "APP_SIGN_OUT",
  APP_SIGN_UP: "APP_SIGN_UP",
  APP_REFLINK: "APP_REFLINK",
};
