export const ETHER = '1000000000000000000';
export const GWEI  = '1000000000';


export const CHANGE =  "CHANGE";
export const TOGGLE_SIDEBAR =  "TOGGLE_SIDEBAR";
export const TOGGLE_SIDEBAR_DROPDOWN =  "TOGGLE_SIDEBAR_DROPDOWN";
export const TOGGLE_SIDEBAR_CRYPTO_DROPDOWN =  "TOGGLE_SIDEBAR_CRYPTO_DROPDOWN";


export const APP_LOADING_START = 'APP_LOADING_START';
export const APP_LOADING_STOP = 'APP_LOADING_STOP';
export const APP_INIT_SUCCESS = 'APP_INIT_SUCCESS';
export const APP_ERROR = 'APP_ERROR';
export const APP_ERROR_CLOSE = 'APP_ERROR_CLOSE';
export const APP_INFO = 'APP_INFO';
export const APP_INFO_CLOSE = 'APP_INFO_CLOSE';

export const APP_TRANSACTION_SUCCESS = 'APP_TRANSACTION_SUCCESS';

export const APP_BALANCE_SUCCESS = 'APP_BALANCE_SUCCESS';
export const APP_EXCHANGE_RATES_SUCCESS = 'APP_EXCHANGE_RATES_SUCCESS';
export const APP_GAS_PRICE_SUCCESS = 'APP_GAS_PRICE_SUCCESS';

export const APP_ASSETS_SUCCESS = 'APP_ASSETS_SUCCESS';
export const APP_ASSET_ADD = 'APP_ASSETS_ADD';
export const APP_ASSET_DELETE = 'APP_ASSET_DELETE';
export const APP_ADDRESSBOOK_SUCCESS = 'APP_ADDRESSBOOK_SUCCESS';
export const APP_ADDRESSBOOK_ADD = 'APP_ADDRESSBOOK_ADD';
export const APP_ADDRESSBOOK_EDIT = 'APP_ADDRESSBOOK_EDIT';
export const APP_ADDRESSBOOK_DELETE = 'APP_ADDRESSBOOK_DELETE';
export const APP_SETTING_SET = 'APP_SETTING_SET';

export const APP_QRCODE = 'APP_QRCODE';

export const APP_REDIRECT = 'APP_REDIRECT';
export const APP_REDIRECT_SUCCESS = 'APP_REDIRECT_SUCCESS';



export const NETWORK_INIT_START = 'NETWORK_INIT_START';
export const NETWORK_INIT_SUCCESS = 'NETWORK_INIT_SUCCESS';
export const NETWORK_INIT_FAILED = 'NETWORK_INIT_FAILED';
export const NETWORK_CHANGE_SUCCESS = 'NETWORK_CHANGE_SUCCESS';
export const NETWORK_GAS_PRICE_INIT_SUCCESS = 'NETWORK_GAS_PRICE_INIT_SUCCESS';
export const NETWORK_EXCHANGE_RATES_INIT_SUCCESS = 'NETWORK_EXCHANGE_RATES_INIT_SUCCESS';

export const WALLET_CHANGE = 'WALLET_CHANGE';
export const WALLET_BALANCE_RELOAD_SUCCESS = 'WALLET_BALANCE_RELOAD_SUCCESS';



export const DEVAPP_INIT_START = 'DEVAPP_INIT_START';
export const DEVAPP_INIT_SUCCESS = 'DEVAPP_INIT_SUCCESS';
export const DEVAPP_INIT_FAILED = 'DEVAPP_INIT_FAILED';
export const DEVAPP_CLEAN = 'DEVAPP_CLEAN';

export const DEVAPP_ADD = 'DEVAPP_ADD';
export const DEVAPP_DELETE = 'DEVAPP_DELETE';
export const DEVAPP_FAILED = 'DEVAPP_FAILED';


export const BOOK_INIT_START = 'BOOK_INIT_START';
export const BOOK_INIT_SUCCESS = 'BOOK_INIT_SUCCESS';
export const BOOK_INIT_FAILED = 'BOOK_INIT_FAILED';
export const BOOK_CLEAN = 'BOOK_CLEAN';

export const BOOK_ADD = 'BOOK_ADD';
export const BOOK_DELETE = 'BOOK_DELETE';




export const CONFIRM_START = 'CONFIRM_START';
export const CONFIRM_SUCCESS = 'CONFIRM_SUCCESS';
export const CONFIRM_ERROR = 'CONFIRM_ERROR';

export const CONFIRM_LOAD_START = 'CONFIRM_LOAD_START';
export const CONFIRM_LOAD_SUCCESS = 'CONFIRM_LOAD_SUCCESS';
export const CONFIRM_LOAD_ERROR = 'CONFIRM_LOAD_ERROR';


export const CURRENCIES = ['USD','EUR','PLN'];
export const CURRENCIES_COUNTRIES_CODES = {'USD': 'us', 'EUR': 'european_union', 'PLN': 'pl'};


export const TRANSACTION_STATUSES = { 10 : "New", 20: "Processing", 30: "Open", 40: "Closed", 50: "Finished", 60: "Canceled"  };

export const DATE_AND_TIME_FORMAT = 'MMMM-DD-YYYY hh:mm:SS A (Z)';



export const DEFAULT_GAS_LIMIT= 30000;
export const DEFAULT_GAS_LIMIT_TOKEN= 100000;









